/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PajamaRouteImport } from './routes/pajama'
import { Route as SneakersRouteImport } from './routes/sneakers'
import { Route as SweatshirtRouteImport } from './routes/sweatshirt'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAbandonedRouteImport } from './routes/admin.abandoned'
import { Route as AdminBlockedRouteImport } from './routes/admin.blocked'
import { Route as AdminHoodieComboStockRouteImport } from './routes/admin.hoodie-combo-stock'
import { Route as AdminPajamaStockRouteImport } from './routes/admin.pajama-stock'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSneakersStockRouteImport } from './routes/admin.sneakers-stock'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminSweatshirtStockRouteImport } from './routes/admin.sweatshirt-stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PajamaRoute = PajamaRouteImport.update({
  id: '/pajama',
  path: '/pajama',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersRoute = SneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SweatshirtRoute = SweatshirtRouteImport.update({
  id: '/sweatshirt',
  path: '/sweatshirt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedRoute = AdminAbandonedRouteImport.update({
  id: '/abandoned',
  path: '/abandoned',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlockedRoute = AdminBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoodieComboStockRoute = AdminHoodieComboStockRouteImport.update({
  id: '/hoodie-combo-stock',
  path: '/hoodie-combo-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPajamaStockRoute = AdminPajamaStockRouteImport.update({
  id: '/pajama-stock',
  path: '/pajama-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSneakersStockRoute = AdminSneakersStockRouteImport.update({
  id: '/sneakers-stock',
  path: '/sneakers-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSweatshirtStockRoute = AdminSweatshirtStockRouteImport.update({
  id: '/sweatshirt-stock',
  path: '/sweatshirt-stock',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/pajama': typeof PajamaRoute
  '/sneakers': typeof SneakersRoute
  '/sweatshirt': typeof SweatshirtRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/hoodie-combo-stock': typeof AdminHoodieComboStockRoute
  '/admin/pajama-stock': typeof AdminPajamaStockRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sneakers-stock': typeof AdminSneakersStockRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/sweatshirt-stock': typeof AdminSweatshirtStockRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pajama': typeof PajamaRoute
  '/sneakers': typeof SneakersRoute
  '/sweatshirt': typeof SweatshirtRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/hoodie-combo-stock': typeof AdminHoodieComboStockRoute
  '/admin/pajama-stock': typeof AdminPajamaStockRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sneakers-stock': typeof AdminSneakersStockRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/sweatshirt-stock': typeof AdminSweatshirtStockRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/pajama': typeof PajamaRoute
  '/sneakers': typeof SneakersRoute
  '/sweatshirt': typeof SweatshirtRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/blocked': typeof AdminBlockedRoute
  '/admin/hoodie-combo-stock': typeof AdminHoodieComboStockRoute
  '/admin/pajama-stock': typeof AdminPajamaStockRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sneakers-stock': typeof AdminSneakersStockRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/sweatshirt-stock': typeof AdminSweatshirtStockRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/pajama'
    | '/sneakers'
    | '/sweatshirt'
    | '/admin/abandoned'
    | '/admin/blocked'
    | '/admin/hoodie-combo-stock'
    | '/admin/pajama-stock'
    | '/admin/settings'
    | '/admin/sneakers-stock'
    | '/admin/stock'
    | '/admin/sweatshirt-stock'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pajama'
    | '/sneakers'
    | '/sweatshirt'
    | '/admin/abandoned'
    | '/admin/blocked'
    | '/admin/hoodie-combo-stock'
    | '/admin/pajama-stock'
    | '/admin/settings'
    | '/admin/sneakers-stock'
    | '/admin/stock'
    | '/admin/sweatshirt-stock'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/pajama'
    | '/sneakers'
    | '/sweatshirt'
    | '/admin/abandoned'
    | '/admin/blocked'
    | '/admin/hoodie-combo-stock'
    | '/admin/pajama-stock'
    | '/admin/settings'
    | '/admin/sneakers-stock'
    | '/admin/stock'
    | '/admin/sweatshirt-stock'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  PajamaRoute: typeof PajamaRoute
  SneakersRoute: typeof SneakersRoute
  SweatshirtRoute: typeof SweatshirtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pajama': {
      id: '/pajama'
      path: '/pajama'
      fullPath: '/pajama'
      preLoaderRoute: typeof PajamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers': {
      id: '/sneakers'
      path: '/sneakers'
      fullPath: '/sneakers'
      preLoaderRoute: typeof SneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweatshirt': {
      id: '/sweatshirt'
      path: '/sweatshirt'
      fullPath: '/sweatshirt'
      preLoaderRoute: typeof SweatshirtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned': {
      id: '/admin/abandoned'
      path: '/abandoned'
      fullPath: '/admin/abandoned'
      preLoaderRoute: typeof AdminAbandonedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocked': {
      id: '/admin/blocked'
      path: '/blocked'
      fullPath: '/admin/blocked'
      preLoaderRoute: typeof AdminBlockedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hoodie-combo-stock': {
      id: '/admin/hoodie-combo-stock'
      path: '/hoodie-combo-stock'
      fullPath: '/admin/hoodie-combo-stock'
      preLoaderRoute: typeof AdminHoodieComboStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pajama-stock': {
      id: '/admin/pajama-stock'
      path: '/pajama-stock'
      fullPath: '/admin/pajama-stock'
      preLoaderRoute: typeof AdminPajamaStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sneakers-stock': {
      id: '/admin/sneakers-stock'
      path: '/sneakers-stock'
      fullPath: '/admin/sneakers-stock'
      preLoaderRoute: typeof AdminSneakersStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sweatshirt-stock': {
      id: '/admin/sweatshirt-stock'
      path: '/sweatshirt-stock'
      fullPath: '/admin/sweatshirt-stock'
      preLoaderRoute: typeof AdminSweatshirtStockRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbandonedRoute: typeof AdminAbandonedRoute
  AdminBlockedRoute: typeof AdminBlockedRoute
  AdminHoodieComboStockRoute: typeof AdminHoodieComboStockRoute
  AdminPajamaStockRoute: typeof AdminPajamaStockRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSneakersStockRoute: typeof AdminSneakersStockRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminSweatshirtStockRoute: typeof AdminSweatshirtStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedRoute: AdminAbandonedRoute,
  AdminBlockedRoute: AdminBlockedRoute,
  AdminHoodieComboStockRoute: AdminHoodieComboStockRoute,
  AdminPajamaStockRoute: AdminPajamaStockRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSneakersStockRoute: AdminSneakersStockRoute,
  AdminStockRoute: AdminStockRoute,
  AdminSweatshirtStockRoute: AdminSweatshirtStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  PajamaRoute: PajamaRoute,
  SneakersRoute: SneakersRoute,
  SweatshirtRoute: SweatshirtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
