CREATE TYPE public.app_role AS ENUM ('admin');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own roles readable" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE TABLE public.product_variants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  size text NOT NULL CHECK (size IN ('M','L','XL','XXL')),
  color_name text NOT NULL,
  color_hex text NOT NULL DEFAULT '#000000',
  image_url text,
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (size, color_name)
);
GRANT SELECT ON public.product_variants TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_variants TO authenticated;
GRANT ALL ON public.product_variants TO service_role;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "variants public read" ON public.product_variants FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage variants" ON public.product_variants FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE,
  customer_name text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  district text,
  note text,
  total_amount integer NOT NULL DEFAULT 999,
  delivery_charge integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  courier_consignment_id text,
  courier_tracking_code text,
  courier_status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins manage orders" ON public.orders FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
  size text NOT NULL,
  color_name text NOT NULL,
  qty integer NOT NULL DEFAULT 1 CHECK (qty > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;
GRANT ALL ON public.order_items TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins manage order items" ON public.order_items FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.settings (
  key text PRIMARY KEY,
  value text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.settings TO authenticated;
GRANT ALL ON public.settings TO service_role;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "settings public read" ON public.settings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage settings" ON public.settings FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

INSERT INTO public.settings (key, value) VALUES ('fb_pixel_id', ''), ('combo_price', '999'), ('combo_qty', '5');

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER trg_variants_updated BEFORE UPDATE ON public.product_variants FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER trg_orders_updated BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.product_variants (size, color_name, color_hex, stock, sort_order) VALUES
('M','Black','#111111',12,1),('M','White','#f8f8f8',10,2),('M','Navy Blue','#1b2a4a',8,3),('M','Maroon','#5d1a25',6,4),('M','Olive','#5a6136',7,5),('M','Sky Blue','#87b7d9',9,6),('M','Grey','#8a8a8a',5,7),('M','Coffee','#6f4e37',4,8),
('L','Black','#111111',15,1),('L','White','#f8f8f8',12,2),('L','Navy Blue','#1b2a4a',10,3),('L','Maroon','#5d1a25',7,4),('L','Olive','#5a6136',6,5),('L','Sky Blue','#87b7d9',8,6),('L','Grey','#8a8a8a',9,7),('L','Mustard','#c9a227',5,8),
('XL','Black','#111111',11,1),('XL','White','#f8f8f8',9,2),('XL','Navy Blue','#1b2a4a',7,3),('XL','Maroon','#5d1a25',5,4),('XL','Olive','#5a6136',6,5),('XL','Sky Blue','#87b7d9',4,6),('XL','Grey','#8a8a8a',8,7),('XL','Bottle Green','#0b3d2e',6,8),
('XXL','Black','#111111',8,1),('XXL','White','#f8f8f8',6,2),('XXL','Navy Blue','#1b2a4a',5,3),('XXL','Maroon','#5d1a25',4,4),('XXL','Olive','#5a6136',3,5),('XXL','Grey','#8a8a8a',5,6),('XXL','Coffee','#6f4e37',4,7),('XXL','Bottle Green','#0b3d2e',3,8);